### ISSUE TITLE
SDK Version in tiapp.xml

### ISSUE THREAD

**Issue by ghost** [appcelerator-developer-relations/appc-sample-ti500#1]
There is an error when you clone this repo and try to build.  Should the sdk version be:

5.2.0.GA?

In the tiapp.xml file it is 5.0.2.GA

Thanks, awesome platform.

**Comment by FokkeZB** [comment]
What's the error?

This sample is for Ti 5.0.x so it should be build with the latest 5.0.x and is not guaranteed to work with older or newer major/minor SDK versions.

**Comment by ghost** [comment]
Our mistake, must have been referencing a different link.  All looks good!  Thanks, sorry.
